# server port config
server:
  port: 8888

# oracle driver config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: C##RESTAURANT
    password: RESTAURANT
    hikari:
      auto-commit: false

  # jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true
        
  # 업로드 파일 크기 제한
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:\images
      max-file-size: 10MB
      max-request-size: 10MB


